TITLE hodgkin_huxley_Na

COMMENT
This file was generated by NEMO (http://wiki.call-cc.org/nemo) version 9.0 on Thu Oct 23 14:06:12 2014

ENDCOMMENT



NEURON {


  RANGE comp19_Vrest, comp19_V_t, comp20_C, Na_erev, Na_gbar, Na_m45, Na_h46
  RANGE i_Na

  RANGE ina, ena



  RANGE Na_C_alpha_h
, Na_B_alpha_h, Na_A_alpha_h, Na_C_beta_h, Na_B_beta_h, Na_A_beta_h, Na_C_alpha_m, Na_B_alpha_m, Na_A_alpha_m, Na_C_beta_m
  RANGE Na_B_beta_m
, Na_A_beta_m, Na_erev
  USEION na READ ena WRITE ina 


}


FUNCTION Na_bmf (v) {

  Na_bmf  =  Na_A_beta_m * exp(-(v + -(Na_B_beta_m)) / Na_C_beta_m)

} 



FUNCTION Na_amf (v) {

  Na_amf  =  
  Na_A_alpha_m * 
    (v + -(Na_B_alpha_m)) / (1.0 + -(exp(-(v + -(Na_B_alpha_m)) / Na_C_alpha_m)))

} 



FUNCTION Na_bhf (v) {

  Na_bhf  =  
  Na_A_beta_h / (1.0 + exp(-(v + -(Na_B_beta_h)) / Na_C_beta_h))

} 



FUNCTION Na_ahf (v) {

  Na_ahf  =  Na_A_alpha_h * exp(-(v + -(Na_B_alpha_h)) / Na_C_alpha_h)

} 





PARAMETER {
  Na_g  =  0.12

  Na_e  =  50.0

  Na_erev  =  50.0

  comp19_Vrest  =  -65.0

  Na_A_alpha_m  =  0.1

  comp20_C  =  1.0

  Na_A_alpha_h  =  0.07

  Na_C_alpha_h  =  20.0

  Na_C_alpha_m  =  10.0

  Na_gbar  =  0.12

  Na_B_alpha_h  =  -65.0

  Na_B_alpha_m  =  -40.0

  Na_C_beta_m  =  18.0

  Na_C_beta_h  =  10.0

  Na_A_beta_m  =  4.0

  comp19_V_t  =  -35.0

  Na_A_beta_h  =  1.0

  Na_B_beta_m  =  -65.0

  Na_B_beta_h  =  -35.0


}



STATE {
  Na_h46C

  Na_h46O

  Na_m45C

  Na_m45O

  Na_h46

  Na_m45


}



ASSIGNED {
  v

  ina

  ena

  i_Na


}


PROCEDURE asgns () {
  ena  =  Na_erev


}



PROCEDURE reactions () {
  Na_h46  =  Na_h46O

  Na_m45  =  Na_m45O


}




BREAKPOINT {

  SOLVE states METHOD cnexp



   reactions()

  i_Na  =  (Na_gbar * Na_m45 ^ 3.0 * Na_h46) * (v - Na_erev)

  ina  =  i_Na


}
DERIVATIVE states {
  LOCAL v100, v102


  asgns()


  v100  =  Na_m45O
                             Na_m45O'  =  (1.0 - v100) * (Na_amf(v)) - Na_m45O * Na_bmf(v)

  v102  =  Na_h46O
                             Na_h46O'  =  (1.0 - v102) * (Na_ahf(v)) - Na_h46O * Na_bhf(v)


}






INITIAL {


  asgns()

	  
  Na_m45  =  
                             (Na_amf(comp19_Vrest)) / (Na_amf(comp19_Vrest) + Na_bmf(comp19_Vrest))

  Na_m45O  =  Na_m45

  Na_h46  =  
                             (Na_ahf(comp19_Vrest)) / (Na_ahf(comp19_Vrest) + Na_bhf(comp19_Vrest))

  Na_h46O  =  Na_h46


	  


	  
}



