TITLE hodgkin_huxley_Leak

COMMENT
This file was generated by NEMO (http://wiki.call-cc.org/nemo) version 9.0 on Thu Oct 23 14:06:12 2014

ENDCOMMENT



NEURON {


  RANGE comp94_Vrest, comp94_V_t, comp95_C, Leak_gbar, Leak_erev
  RANGE i_Leak

  RANGE e



  RANGE Leak_erev

  NONSPECIFIC_CURRENT i


}




PARAMETER {
  comp94_Vrest  =  -65.0

  Leak_e  =  -54.4

  Leak_g  =  0.0003

  comp94_V_t  =  -35.0

  Leak_erev  =  -54.4

  Leak_gbar  =  0.0003

  comp95_C  =  1.0


}




ASSIGNED {
  v

  i

  e

  i_Leak


}


PROCEDURE asgns () {
  e  =  Leak_erev


}





BREAKPOINT {





  i_Leak  =  Leak_gbar * (v - Leak_erev)

  i  =  i_Leak


}






