TITLE hodgkin_huxley_K

COMMENT
This file was generated by NEMO (http://wiki.call-cc.org/nemo) version 9.0 on Thu Oct 23 14:06:12 2014

ENDCOMMENT



NEURON {


  RANGE comp61_Vrest, comp61_V_t, comp62_C, K_gbar, K_erev, K_m79
  RANGE i_K

  RANGE ik, ek



  RANGE K_C_alpha_n
, K_B_alpha_n, K_A_alpha_n, K_C_beta_n, K_B_beta_n, K_A_beta_n, K_erev
  USEION k READ ek WRITE ik 


}


FUNCTION K_bnf (v) {

  K_bnf  =  K_A_beta_n * exp(-(v + -(K_B_beta_n)) / K_C_beta_n)

} 



FUNCTION K_anf (v) {

  K_anf  =  
  K_A_alpha_n * 
    (v + -(K_B_alpha_n)) / 
      (1.0 + -(exp(-(v + -(K_B_alpha_n)) / K_C_alpha_n)))

} 





PARAMETER {
  K_A_alpha_n  =  0.01

  K_A_beta_n  =  0.125

  comp61_V_t  =  -35.0

  K_B_alpha_n  =  -55.0

  K_gbar  =  0.036

  comp61_Vrest  =  -65.0

  K_B_beta_n  =  -65.0

  comp62_C  =  1.0

  K_C_alpha_n  =  10.0

  K_erev  =  -77.0

  K_e  =  -77.0

  K_g  =  0.036

  K_C_beta_n  =  80.0


}



STATE {
  K_m79C

  K_m79O

  K_m79


}



ASSIGNED {
  v

  ik

  ek

  i_K


}


PROCEDURE asgns () {
  ek  =  K_erev


}



PROCEDURE reactions () {
  K_m79  =  K_m79O


}




BREAKPOINT {

  SOLVE states METHOD cnexp



   reactions()

  i_K  =  (K_gbar * K_m79 ^ 4.0) * (v - K_erev)

  ik  =  i_K


}
DERIVATIVE states {
  LOCAL v104


  asgns()


  v104  =  K_m79O
                             K_m79O'  =  (1.0 - v104) * (K_anf(v)) - K_m79O * K_bnf(v)


}






INITIAL {


  asgns()

	  
  K_m79  =  
                             (K_anf(comp61_Vrest)) / (K_anf(comp61_Vrest) + K_bnf(comp61_Vrest))

  K_m79O  =  K_m79


	  


	  
}



